Algoritmo "ExemploRepeticaoRepita"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jailson
// Data atual  : 26/09/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


   repita
      Escreval(contadora)
      contadora<-contadora+1
   ate contadora>=5

Fimalgoritmo